### ISSUE TITLE
GitTogether Medellín

### ISSUE THREAD

**Issue by AndreaGriffiths11** [gittogethers/devopsdaysmedellin24#3]
![WhatsApp Image 2024-05-13 at 12 51 48](https://github.com/gittogethers/devopsdaysmedellin24/assets/20666190/81f9c534-f439-4218-957c-dcb0b9c7475a)

**Comment by easalynas** [comment]
🥰

**Comment by elizarangelm** [comment]
Gracias Andrea, Vanessa y Marian por gestionar este evento tan inspirador🔥💙

**Comment by Saraapl** [comment]
Hola!!

**Comment by TeoEchavarria** [comment]
LOCURAAA!!!

**Comment by QuintoFelipe** [comment]
🥑🥑

**Comment by Karlosll91** [comment]
Muchas gracias por este evento! Aprendí mucho y genial lo del student pack!

**Comment by jolual2747** [comment]
Genial el espacio!

**Comment by AlexandroMunera** [comment]
Que gran evento... Gracias 😎

**Comment by LogisApp** [comment]
Congratulations

**Comment by SantiRendon** [comment]
Viva el código

**Comment by jmblack15** [comment]
Wow que evento!! Mujeres muy tesas!!

**Comment by anamariaroman** [comment]
Gracias por este evento y el aprendizaje compartido🤩

**Comment by julianfrancor** [comment]
Un comentario

**Comment by AndresHadechine** [comment]
Buenass <3

**Comment by Shanic0120** [comment]
Hola!!

**Comment by jahirfiquitiva** [comment]
hola 😄 excelente evento! 👏👏

**Comment by Mila-Ag** [comment]
Gran evento!!

**Comment by Wiferpagri** [comment]
Hi everyone

**Comment by Marlondot** [comment]
Hermoso este evento. Gracias por todo lo compartido 💜💜💜

**Comment by luisdaka** [comment]
Heyyy  🔥🔥🔥🔥

**Comment by vmunozm** [comment]
Excelente evento!

**Comment by suduquem** [comment]
Excelente evento. Muchas gracias 💛

**Comment by acpuche** [comment]
Hi ❤️

**Comment by jeanneth2188** [comment]
Gracias por estos espacios 💕💕

**Comment by jhovanbiker** [comment]
El mejor evento 💪🏼🔥

**Comment by amonsalv** [comment]
Gracias por el evento! Espectacular!!!!

**Comment by xaca** [comment]
Muy buen evento 🫶

**Comment by Manuela11ocampo** [comment]
Excelente evento, me encanta ver gente tan Crack en un mismo lugar!

**Comment by MarieGomezCode** [comment]
Sever Port 8080

**Comment by Dioprz** [comment]
🔥🔥🔥

**Comment by juduranr** [comment]
Hola Git Together Med 🎉

**Comment by SantiGarzonD** [comment]
Gracias por esta genial primera experiencia de nuestra nueva comunidad ♥️

**Comment by Jhonatant98** [comment]
Holaaa

**Comment by Breims** [comment]
☕☕☕😎

**Comment by JhonEderMC** [comment]
Hi 👽

**Comment by EandreaSanchez** [comment]
Gracias por este evento!

**Comment by AeroFrankGonzalez** [comment]
Gracias por el evento!! Creen un Instagram

**Comment by verordgz25** [comment]
Welcome to Medellin GitHub community 💖

**Comment by lucy-ricaurte** [comment]
muy buenas charlas, aprendí mucho 😃

**Comment by sgomezsal** [comment]
Quiero expresar mi más sincero agradecimiento a la comunidad de GitHub. Su dedicación, colaboración y apoyo han sido fundamentales para el éxito de nuestros proyectos. Gracias a todos los desarrolladores que contribuyen desinteresadamente, a los mantenedores que velan por la calidad y a cada miembro que hace de esta comunidad un lugar increíble para aprender y crecer. ¡Gracias, GitHub community!

**Comment by jmcada2503** [comment]
Muchas gracias por todoo!

**Comment by acpuche** [comment]
Holaaaaa 
Gracias

**Comment by emazou** [comment]
Muchas gracias por este evento tan inspirador, salgo de aquí con muchos aprendizajes sobre cómo impactar comunidades ❤️❤️

**Comment by davidroldan211** [comment]
👋

**Comment by Uru198** [comment]
Un parche de evento 😎

**Comment by juansebasdev** [comment]
Gracias por este excelente evento 👌

**Comment by andresospina1989** [comment]
Excelente evento

**Comment by jhovanbiker** [comment]
Gracias por el evento 🔥

**Comment by angiefrancop** [comment]
Gracias por la charla, genial!

**Comment by greysy** [comment]
Muchos aprendizajes, super organización y grandes cracks invotad@s. Tnks!!!!

**Comment by edseldim** [comment]
Muchas gracias!!

**Comment by lucy-ricaurte** [comment]
Genial el evento, aprendí mucho

**Comment by muygrafico** [comment]
😊👋 ¡Gracias por el evento!

**Comment by lucy-ricaurte** [comment]
Gracias por el evento

**Comment by Annaseanna** [comment]
Súper chevere el evento. Gracias por hacer comunidad c:

**Comment by xgiosebsx** [comment]
Git git git en Medellín

**Comment by DanielaVL** [comment]
Muchas gracias por tan increíble evento❤️✨

**Comment by jahirfiquitiva** [comment]
Estuvo genial todo! 👏 qué buen evento 😄

**Comment by Jhonatant98** [comment]
Cracks

**Comment by jahirfiquitiva** [comment]
Genial este espacio para aprender más y unirse a la comunidad

**Comment by Wiferpagri** [comment]
Quién para Data Science

**Comment by jhonescuderog** [comment]
jhonescuderog

**Comment by jhovanbiker** [comment]
Exelente evento 💪🏼🔥

**Comment by JuanDezMo** [comment]
Great Event! ⚡

**Comment by lasanchezgi** [comment]
Buenas noches a todos, 
Muy feliz de participar de la nueva comunidad 🐱🐙
Podemos conectar en LinkedIn, estoy como @laurasanchezgi 🤓
Un abrazo 🤗

**Comment by jhovanbiker** [comment]
Cracks 🔥

**Comment by TeoEchavarria** [comment]
[Data Science, ML and AI](https://teoechavarria.github.io) - Mateo Echavarria 

@TeoEchavarria - En todas las redes sociales

**Comment by juanes1014** [comment]
Gracias por la charla ❤️

**Comment by daniel-beta** [comment]
Excelente evento, muchas gracias!
[danielbetancur.com](danielbetancur.com)

**Comment by jaidersant** [comment]
Aprendí a erca triplee

**Comment by jaidersant** [comment]
Aprendí acerca de triple e

**Comment by AndreaGriffiths11** [comment]
¡Quiero expresar mis más sinceros, agradecimientos a todos ustedes por su presencia en este evento, a pesar de las inclemencias del tiempo, aprecio mucho el esfuerzo que han supuesto para atender, espero este sea el primero de muchos eventos! ✨
