### ISSUE TITLE
DevOps Days Medellin - Participa en las rifas, dejando un comentario en este Issue

### ISSUE THREAD

**Issue by AndreaGriffiths11** [gittogethers/devopsdaysmedellin24#4]
<img src="https://github.com/gittogethers/devopsdaysmedellin24/assets/20666190/422ed8d5-ff9c-42f8-a4a5-2b00d0fafd0b" width="300">

🎉 ¡Atención todos los asistentes de DevOpsDays Medellín 2024! 🎉

Prepárense para el momento más esperado del evento: ¡El Sorteo Final! 🏆✨

📅 Fecha: Viernes, 24 de mayo
⏰ Hora: 16:45
📍 Lugar: Teatro Mayor

Después de dos días increíbles llenos de charlas inspiradoras, talleres prácticos y networking con la comunidad DevOps, ha llegado el momento de cerrar con broche de oro. 🌟

En este sorteo final, tendremos premios espectaculares que no querrás perderte:

1. 🎒 **Invertocat MiiR® Laptop Backpack**: La mochila definitiva para todos tus viajes y aventuras diarias.
2. 🥤 **Invertocat Asobu Marina Tumbler**: Bebe con estilo con el vaso térmico invertible Invertocat Asobu 2 en 1, el compañero de viaje definitivo para personas tecnológicas en movimiento.
3. :octocat: **Figurina de Mona**: ¿Necesitas algo de inspiración mientras codificas? Esta figurita de Mona de 5 pulgadas, con un tentáculo extendido de manera servicial, ofrece las vibraciones creativas que necesitas para sacar tu proyecto del parque.
4. 🧸 **Mona peluche**: Mona de peluche - diseñada para brindar las caricias que tú o tu pequeño necesitan para brillar.

Para participar, asegúrate de haber visitado nuestro stand de GitHub durante el evento y haber completado tu inscripción. Recuerda estar presente en el Teatro Mayor a las 16:45 del viernes 24 de mayo para el anuncio de los ganadores. ¡No te vayas antes, o podrías perder tu oportunidad de llevarte a casa uno de estos increíbles premios! 🎈

Aprovecha estos últimos momentos del evento para hacer networking, intercambiar contactos y despedirte de tus nuevos amigos de la comunidad DevOps. 🤝💬

¡Nos vemos en el Sorteo Final! ¡Buena suerte a todos! 🌟

**Comment by ag1111** [comment]
🍀

**Comment by Orlando2601** [comment]
~/

**Comment by lejito** [comment]
GitHub works! 😸

**Comment by javier1O** [comment]
Ready to win!

**Comment by ChristYela** [comment]
Estuvo bueno el evento de la inauguración de la comunidad de gut togethers en Medellin

**Comment by Aldairng** [comment]
this is not an issue! Ready to win it

**Comment by jboteros** [comment]
![IMG_1446](https://github.com/gittogethers/devopsdaysmedellin24/assets/20464735/306acc51-2d74-4e91-b746-523d489bf7f3)

**Comment by tictologo** [comment]
Let's do it!

**Comment by geinnertucto** [comment]
I’m ready!!

**Comment by EduardoChaka87** [comment]
Con git hasta el fin

**Comment by luisssegura3** [comment]
👀🍀🎱🤞🏽

**Comment by stevenyepes** [comment]
Let’s go with copilot

**Comment by Santiago1023** [comment]
Manifestando ganarme el bolso🚀🚀🙏

**Comment by edsuarezs** [comment]
DevOps Days

**Comment by cristianmontoyaalt** [comment]
🫡

**Comment by Lexuzops** [comment]
Si no lo encuentras en git es que estás buscando mal 😬

**Comment by jecarvajal** [comment]
Jecarvajal presente!

**Comment by ManuelEcheverri** [comment]
👨‍💻👨‍💻

**Comment by JamesChe91** [comment]
🤘🤖👾

**Comment by PiipeMan** [comment]
🫠🤔🤔🤔nice

**Comment by anseanar** [comment]
👍🏻

**Comment by dcorream** [comment]
Go DevOps!!! 🤟🏼

**Comment by JofMendz** [comment]
Git pull origin premio!!! 😁

**Comment by juanhoyos20** [comment]
Ready to DevOps day!

**Comment by mahc30** [comment]
aaaaaaaaaaaaa

**Comment by CRODR35** [comment]
Team DevOps 🤟

**Comment by RCu3llar** [comment]
🐙

**Comment by julianapicon** [comment]
GitHub the best! Lovely

**Comment by tstng** [comment]
💻📱🎉🎉

**Comment by Jperico** [comment]
Go to the learning and win with all the apps of githubs.

**Comment by Shiroke-013** [comment]
Lets Go!!!

**Comment by santyarboleda** [comment]
Go github!

**Comment by jdiegoisaza** [comment]
Una excelente presentación

**Comment by stivenatehortua** [comment]
Go github!

**Comment by cristianu90118** [comment]
Go github!! 💪💪

**Comment by olsmca** [comment]
Vamos por eso 👍🏼

**Comment by YuliethZg7** [comment]
Go github!! 🤳👏

**Comment by DanielaVL** [comment]
GitHub lover💘✨

**Comment by lpfalcon** [comment]
Lista para participar

**Comment by 3htp-sebasguisao** [comment]
I 💙 GitHub

**Comment by yucaci24** [comment]
GutHub en DevOps Days Medellín 2024!!! 🎉

**Comment by gmfnem** [comment]
Hola Mona

**Comment by ValentinaCG99** [comment]
Genial, un evento espectacular, deseo ganarme el peluchito 🙏🏼🤗

**Comment by LordArshen** [comment]
Devops days 2024

**Comment by thenickforero** [comment]
💖

**Comment by jcorreahotmail** [comment]
Un magnifico evento, gracias por apoyar Github!!!

**Comment by Ycasall** [comment]
De nuevo contento de encontrarme con GitHub, Manuel Briceño que energía volvernos a ver.

**Comment by Leo-Avalos** [comment]
It works on my machine 🤷🏻‍♂️

**Comment by Juansecod** [comment]
Love it, Github is my religion in dev 😼

**Comment by Basketking36** [comment]
Github is the Best place.

**Comment by jSebastianNieto** [comment]
Go GitHub!! 💯

**Comment by joancgr** [comment]
Great, good gob

**Comment by josephrojas** [comment]
Que buen evento :D

**Comment by lfdaach** [comment]
Excelente evento 😊

**Comment by PaulaOspina95** [comment]
Devops days!!!

**Comment by juniortib1986** [comment]
GH rocks!

**Comment by serginho32165** [comment]
⚡️

**Comment by carlosramillan94** [comment]
Ready to win!!

**Comment by Jhonnier20** [comment]
GitHub is Power! 🔥

**Comment by ChristianFlor** [comment]
GitHub is life🤘
Proudly GitHub 🙌

**Comment by jguillermo6** [comment]
Hello world! 👋🏻

**Comment by ovas04** [comment]
Go GH!

**Comment by vioru** [comment]
🤞🏾🤞🏾🤞🏾🔥🌟💖

**Comment by andrez47** [comment]
Thanks! Gracias!

**Comment by deig0sv** [comment]
Hola 🪲

**Comment by lvega-root** [comment]
GitTogether Lima!

**Comment by ayalamac** [comment]
Hello world

**Comment by santimonsalvec** [comment]
Genial verlos en DevOps Medellín

**Comment by Igua520** [comment]
😍🖤🎒

**Comment by rarodriguez** [comment]
Excelente ver un stand de github en el evento

**Comment by edanveb** [comment]
Github rocks!! 🔥🔥

**Comment by edanveb** [comment]
Github rocks!! 🔥🔥

**Comment by jesusd-sanchezn** [comment]
Hi

**Comment by guillermo-varela** [comment]
Tactical dot.

**Comment by pabloandresmelo** [comment]
Presente en el devopsday Medellín 2024

**Comment by RickContreras** [comment]
Go!

**Comment by jrodrigop** [comment]
Medellin DevOps days!!

**Comment by camiloss1** [comment]
DOD

**Comment by axellab** [comment]
DevOpsDays Medellín y GitHub 🔥🔥

**Comment by IBIOHAZARDI** [comment]
Rdy to win

**Comment by jhonescuderog** [comment]
Hola

**Comment by LSebastianHR** [comment]
🍀 🍀

**Comment by lscaballero** [comment]
Denme el peluche 🥹

**Comment by SanGeeky** [comment]
Octocat, I love u <3

**Comment by JavaGarcia** [comment]
☝️

**Comment by SMurillo29** [comment]
Devops Medellín 👋

**Comment by Rextery** [comment]
Excelente iniciativa

**Comment by herreradaniel13** [comment]
Devops Medellín 👋

**Comment by lorejimenez117** [comment]
Devops day Medellin 2024

**Comment by ValentinaCG99** [comment]
Me regalan el gatito 😁

**Comment by ValentinaCG99** [comment]
Me regalan el gatito 😁

**Comment by ValentinaCG99** [comment]
Me regalan el gatito 😁 quiero

**Comment by maurosanchezg** [comment]
I was here

**Comment by alejo117lp** [comment]
I will be the winner 🙈😣

**Comment by lorejimenez117** [comment]
I will be the winner

**Comment by dagan01** [comment]
Con moral!

**Comment by andresEspejo-Globant** [comment]
Medellín DevOps Days 😄

**Comment by xcortes** [comment]
DevOps Day Medellín 2024 🐰

**Comment by hermanngalvis** [comment]
:)

**Comment by jcont15** [comment]
Viva GitHub Colombia!

**Comment by Deum14** [comment]
Ese bolso es mío 🤞

**Comment by CristianSeguro** [comment]
😃

**Comment by JoseMen97** [comment]
DevOps😁

**Comment by carlorm3** [comment]
Presente en el devops day 2024

**Comment by sisazago** [comment]
Genial

**Comment by sisazago** [comment]
Genial

**Comment by carlosmoradev** [comment]
CarlosMora here

**Comment by cristian-morales-sm** [comment]
Ready to win

**Comment by jihincap** [comment]
Voy por el bolso!

**Comment by juansarm87** [comment]
Grate event

**Comment by dyany** [comment]
DevOps day 2024

**Comment by jmblack15** [comment]
Wooo 😄

**Comment by afrodriguez68** [comment]
DevOps Medellín 2024!!!💪💪

**Comment by ingjuanfg** [comment]
Puede que sea un issue. Necesito cuál es el AR y ER para proceder a probar. XD

**Comment by isanchezf** [comment]
Esa maleta es mia

**Comment by heimarvega** [comment]
Hola muchas gracias por estar en el evento

**Comment by Andrearestrepo** [comment]
La quiero !!!!

**Comment by anamariaroman** [comment]
Gracias por estar presentes en el DevOps days Medellin 🤩

**Comment by nat55555** [comment]
:nerd_face:

**Comment by CasttleMDev** [comment]
Ay caraaaiii... 

rifa = bolso
print ("quiero el, rifa")

**Comment by carlosbioingeniero** [comment]
👉👈

**Comment by davidag82** [comment]
🙌

**Comment by WelmarChaverra** [comment]
![stand_github](https://github.com/gittogethers/devopsdaysmedellin24/assets/70119747/62432b4e-b7f9-44e8-abc5-d2f379c3a962)

**Comment by jboteros** [comment]
Gracias por los stickers 🤘

![IMG_1504](https://github.com/gittogethers/devopsdaysmedellin24/assets/20464735/ed6f1d66-3af3-4110-8137-71b7dbe955f0)

**Comment by ElmarDott** [comment]
A pleasure to be here at DevOpsDays 2024 Medellin :-)

**Comment by andersoneholguin** [comment]
Very thanks!!!’

**Comment by gorozcoh1** [comment]
I’m ready to win! 🍀✌️

**Comment by LauraTabaresH** [comment]
DevOps Day

**Comment by judigael** [comment]
I like GigHub

**Comment by elizarangelm** [comment]
Amo poder crear comunidad gracias a github!

**Comment by GFRO92** [comment]
🤘🏻💻🖥️🤘🏻

**Comment by grodaz** [comment]
Cool

**Comment by CamiloVelezP** [comment]
Thanks!

**Comment by DiegoRios3455** [comment]
😶

**Comment by ataler1** [comment]
Soy participante

**Comment by jamespp22** [comment]
Espero tener suerte. Gran trabajo!!

**Comment by cruiz7** [comment]
Hola no me ganado nada en el devops day

**Comment by DanielaVL** [comment]
Mucho love por GitHub💜

**Comment by yohanalais** [comment]
Excelente!!!

**Comment by EmmanuelUdeA** [comment]
Amo Github 🫶🏻

**Comment by ValentinaCG99** [comment]
Quiero el gatito 😞🖤

**Comment by ValentinaCG99** [comment]
Quiero el gatito 🤩

**Comment by gsondev** [comment]
GitHub lo mejor! 🥳

**Comment by jhonatantm9** [comment]
Participando!

**Comment by zSarlix** [comment]
A ganar 💖

**Comment by PiloxD** [comment]
Push

**Comment by SnifferNandez** [comment]
FTW!

**Comment by FranciscoJL99** [comment]
si no me lo gano, estaba amañado!!! :(

**Comment by estefannygr** [comment]
Gracias por hacer q el código q se genera, sea más organizado

**Comment by Dango-25** [comment]
![IMG_0257](https://github.com/gittogethers/devopsdaysmedellin24/assets/69904734/672c8cd0-4b9f-4dbf-a2e0-b583249cec8a)

**Comment by Cardona-JE** [comment]
DevOps Day :)

**Comment by verordgz25** [comment]
Excelente evento! El mejor both GitHub

**Comment by EsneiderSM** [comment]
Hello!!

**Comment by andresaguilarjs** [comment]
Hola!

**Comment by EsneiderSM** [comment]
Participar

**Comment by Santiago1023** [comment]
Se fue

**Comment by EdierDavidME** [comment]
Tope
Dani

**Comment by IsisAmaya** [comment]
Hola Mundo!

**Comment by AndreaGriffiths11** [comment]
Por favor dirigirse al stand de GitHub para los premios, debes estar presente para ganar; 🍀 buena suerte

**Comment by dcorream** [comment]
GOAT

**Comment by serginho32165** [comment]
Yo me lo gano ⚡️⚡️

**Comment by xcortes** [comment]
Hola de nuevo

**Comment by lscaballero** [comment]
Le pol dio

**Comment by dcorream** [comment]
Insert comment here

**Comment by afrodriguez68** [comment]
Copilot

**Comment by afrodriguez68** [comment]
Octocat

**Comment by lscaballero** [comment]
Que nervios

**Comment by dcorream** [comment]
HubGit

**Comment by EsneiderSM** [comment]
Josué

**Comment by lscaballero** [comment]
Rápido agonía

**Comment by dcorream** [comment]
DevOps days

**Comment by carlosramillan94** [comment]
Ready to win

**Comment by dcorream** [comment]
Medellin

**Comment by afrodriguez68** [comment]
Mis licencias!!!

**Comment by mmaurogg** [comment]
DevOps days
Saludos

**Comment by DanielaVL** [comment]
💜💜💜

**Comment by diarbelo** [comment]
Diego

**Comment by DanielaVL** [comment]
GitHub lover💜💜⚡️

**Comment by Masebi** [comment]
Vamoos

**Comment by CarlosBaez11** [comment]
Hola mundo

**Comment by belizab02** [comment]
Una bacaneria de dias

**Comment by ChristianFlor** [comment]
Maleta de commits

**Comment by FelipeArredond** [comment]
DevSecOps bancolombia
